language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t nilahomar/react-complex -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true nilahomar/react-complex npm test

after_success:
  - docker build -t nilahomar/multi-client ./client
  - docker build -t nilahomar/multi-nginx ./nginx
  - docker build -t nilahomar/multi-server ./server
  - docker build -t nilahomar/multi-worker ./worker

  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push then to docker hub
  - docker push nilahomar/multi-client
  - docker push nilahomar/multi-nginx
  - docker push nilahomar/multi-server
  - docker push nilahomar/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'eu-central-1'
  app: 'Complex-docker'
  env: 'Complex-docker-env '
  bucket_name: 'elasticbeanstalk-eu-central-1-080480537207'
  bucket_path: 'docker-multi'
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
