deploy:
  provider: elasticbeanstalk
  region: 'eu-central-1'
  app: 'Complex-docker'
  env: 'Complex-docker-env '
  bucket_name: 'elasticbeanstalk-eu-central-1-080480537207'
  bucket_path: 'docker-multi'
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
